### ISSUE TITLE
Lab #3-Error message with text()

### ISSUE THREAD

**Issue by danafuller** [Watts-College/cpp-526-fall-2022#18]
I am trying to add text in the plot that is a number.  It is an identifier for a specific point that is highlighted.  Should I name it a label instead?

`text(x=1924, y=2.7, "2.7",cex=1, col="skyblue")`

Error: unexpected numeric constant in:
"
text(x=1924, y=2.7, "2.7"

**Comment by jacobtnyoung** [comment]
Hi @danafuller!

The code works for me.

```
plot( seq( 1900, 2000, length.out = 10 ), seq( 0, 9) , type = "n" )
text( x=1924, y=2.7, "2.7", cex=1, col="skyblue" )
```

![image](https://user-images.githubusercontent.com/39632608/188928187-5045fbf0-cc60-4604-a9c6-ba79bf8ba308.png)

**Comment by jacobtnyoung** [comment]
Hi @danafuller. I think the issue is that it looks as though you wrote the code in Word and and copy and pasting into the .Rmd file. Note that the error message is about a character after the `"2.7"` in your code.  It "looks" correct, but if you are copy and pasting from Word, it will bring hidden characters. In this case, that is what seems to be happening.

I know you are using Word for the editing, but it is easier to avoid these sorts of issues of you build the code in the .Rmd file or in a text editor.

**Comment by danafuller** [comment]
That is a really good catch.  I will make sure I don't do any cutting and pasting from word again to avoid this!  Thank you!

**Comment by jacobtnyoung** [comment]
Hi @danafuller. Was that the issue?
