### ISSUE TITLE
Lab-01-Neighborhood with most vacant lots/arguments different lengths

### ISSUE THREAD

**Issue by danafuller** [Watts-College/cpp-526-fall-2022#7]
I thought I would try this to determine which neighborhood had the most vacant lots:
table(dat$neighborhood, land_use = "vacant land")

This is the error message I received:
Error in table(dat$neighborhood, land_use = "vacant land") : 
  all arguments must have the same length

I am confused because I don't really understand what it is telling me.

**Comment by jacobtnyoung** [comment]
Hi @danafuller! Good question. You need to use the expression `==` in your statement. The `=` reads as "equals" whereas `==` "exactly equal to". Make sense?

**Comment by jacobtnyoung** [comment]
Try this: `table(dat$neighborhood, land_use == "vacant land")`

**Comment by danafuller** [comment]
Ahh, it's in the details!  Thanks!

**Comment by jacobtnyoung** [comment]
It can be confusing sometimes because `=` can be used as an assignment operator as in `x = 4` being the same as `x<-4`.

**Comment by danafuller** [comment]
I got this error message:
Error in table(dat$neighborhood, land_use == "vacant land") : 
  object 'land_use' not found

I went back and loaded the data again to see if it would recognize the variable after that, but I still get that error.  I am not sure why it won't recognize it as it clearly is one of the variables.

**Comment by jacobtnyoung** [comment]
In your original statement you have: `table(dat$neighborhood, land_use = "vacant land")`. The error is saying that it can't locate the `land_use` object.

That is because `land_use` is not an object in the workspace. What you want is the variable `land_use` in the object `dat`. Right?

Try: `table(dat$neighborhood, dat$land_use = "vacant land")`, noting the inclusion of `dat$` before `land_use`.
